server:
    port: 8003
spring:
    application:
        name: currency-conversion
    cloud:
        config:
            uri: http://localhost:8888
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health
    health:
        circuitbreakers:
            enabled: true
resilience4j:
    circuitbreaker:
        instances:
            currency-conversion:
                automaticTransitionFromOpenToHalfOpenEnabled: true
                event-consumer-buffer-size: 10
                failureRateThreshold: 60
                minimumNumberOfCalls: 6
                permittedNumberOfCallsInHalfOpenState: 2
                registerHealthIndicator: true
                slidingWindowSize: 10
                slidingWindowType: COUNT_BASED
                waitDurationInOpenState: 3s
